In [8]:
# Question 1

# Answer 1

import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
# there is a difference between the data type of variables list_ and array_list.
# variable list_ is a list data type whereas array_list is a numpy n-dimensional array data type

print("List_ variable data type is: ")
print(type(list_),"\r\n")
print("array_list variable data type is: ")
print(type(array_list))


List_ variable data type is: 
<class 'list'> 

array_list variable data type is: 
<class 'numpy.ndarray'>


In [15]:
# Question 2

# Answer 2

for i in list_:
    print("Value in list_: ",i,"\n Data Type: ",type(i),"\r")
    
print("\r\n")
    
for i in array_list:
    print("Value in array_list: ",i,"\n Data Type: ",type(i),"\r")

Value in list_:  1 
 Data Type:  <class 'str'> 
Value in list_:  2 
 Data Type:  <class 'str'> 
Value in list_:  3 
 Data Type:  <class 'str'> 
Value in list_:  4 
 Data Type:  <class 'str'> 
Value in list_:  5 
 Data Type:  <class 'str'> 


Value in array_list:  1 
 Data Type:  <class 'numpy.str_'> 
Value in array_list:  2 
 Data Type:  <class 'numpy.str_'> 
Value in array_list:  3 
 Data Type:  <class 'numpy.str_'> 
Value in array_list:  4 
 Data Type:  <class 'numpy.str_'> 
Value in array_list:  5 
 Data Type:  <class 'numpy.str_'> 


In [19]:
# Quesgtion 3

# Answer 3 -

array_list = np.array(object = list_, dtype = int)

# yes there would be a difference in the data type of the elements present in both the variables, list_ and array_list.
# The elemnts inside the list_ variable would be of string data type, whereas the elements inside array_list would be of numpy integer data type 

for i in list_:
    print("Value in list_: ",i,"\n Data Type: ",type(i),"\r")
    
print("\r\n")


for i in array_list:
    print("Value in array_list: ",i,"\n Data Type: ",type(i),"\r")

Value in list_:  1 
 Data Type:  <class 'str'> 
Value in list_:  2 
 Data Type:  <class 'str'> 
Value in list_:  3 
 Data Type:  <class 'str'> 
Value in list_:  4 
 Data Type:  <class 'str'> 
Value in list_:  5 
 Data Type:  <class 'str'> 


Value in array_list:  1 
 Data Type:  <class 'numpy.int64'> 
Value in array_list:  2 
 Data Type:  <class 'numpy.int64'> 
Value in array_list:  3 
 Data Type:  <class 'numpy.int64'> 
Value in array_list:  4 
 Data Type:  <class 'numpy.int64'> 
Value in array_list:  5 
 Data Type:  <class 'numpy.int64'> 


In [34]:
# Question 4

# Answer 4

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print("num_array is: \n",num_array,"\n")
print("Shape of the num_array is: ",num_array.shape,"\r\n")

print("Size of num_array is: ",num_array.size)

num_array is: 
 [[1 2 3]
 [4 5 6]] 

Shape of the num_array is:  (2, 3) 

Size of num_array is:  6


In [29]:
# Question 5

# Answer 5 - code to create numpy array of 3*3 matrix containing zeros only

arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# Question 6

# Answer 6 - identity matrix of shape (5,5) using numpy function

arr1=np.eye(5,5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])